#!/usr/bin/env bash

[ ! "$XDG_VTNR" -eq 1 ] && source "$HOME/.bashrc"

setfont "$(grep '^FONT=' /etc/vconsole.conf | cut -d'=' -f2)"

if [ "$TERM" = "linux" ]; then
   # gruvbox
   echo -en "\e]P0282828" #black
   echo -en "\e]P8928374" #darkgrey
   echo -en "\e]P1CC241D" #darkred
   echo -en "\e]P9FB4934" #red
   echo -en "\e]P298971A" #darkgreen
   echo -en "\e]PAB8BB26" #green
   echo -en "\e]P3D79921" #brown
   echo -en "\e]PBFABD2F" #yellow
   echo -en "\e]P4458588" #darkblue
   echo -en "\e]PC83A598" #blue
   echo -en "\e]P5B16286" #darkmagenta
   echo -en "\e]PDD3869D" #magenta
   echo -en "\e]P6689D6A" #darkcyan
   echo -en "\e]PE8EC07C" #cyan
   echo -en "\e]P7A89984" #lightgrey
   echo -en "\e]PFEBDBB2" #white
   clear #for background artifacting
fi

export PATH="$PATH:$HOME/.local/bin"

export EDITOR="nvim"
export TERMINAL="st"
export FILE_MANAGER="nnn"
export BROWSER="browser"
export WALLPAPER="$HOME/.local/share/wallpaper"

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

export INPUTRC="${XDG_CONFIG_HOME:-$HOME/.config}/shell/inputrc"
export XINITRC="${XDG_CONFIG_HOME:-$HOME/.config}/x11/xinitrc"
export HISTFILE="${XDG_CONFIG_HOME:-$HOME/.config}/bash/history"
export LESSHISTFILE="-"
export TERMINFO="${XDG_CONFIG_HOME:-$HOME/.config}/st/terminfo"
export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"

export SUDO_ASKPASS="$HOME/.local/bin/askpass"

if [[ -z "${DISPLAY}" && "${XDG_VTNR}" -eq 1 ]]; then
   exec startx "${XINITRC}"
fi
