#!/usr/bin/env bash

. "$HOME/.bashrc"

export PATH="$PATH:$HOME/.local/bin"

export EDITOR="nvim"
export TERMINAL="st"
export FILE_MANAGER="nnn"
export BROWSER="browser"
export WALLPAPER="$HOME/.local/share/wallpaper"

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

export INPUTRC="${XDG_CONFIG_HOME:-$HOME/.config}/shell/inputrc"
export XINITRC="${XDG_CONFIG_HOME:-$HOME/.config}/x11/xinitrc"
export HISTFILE="${XDG_CONFIG_HOME:-$HOME/.config}/bash/history"
export LESSHISTFILE="-"
export TERMINFO="${XDG_CONFIG_HOME:-$HOME/.config}/st/terminfo"
export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"

export SUDO_ASKPASS="$HOME/.local/bin/askpass"

if [[ -z "${DISPLAY}" && "${XDG_VTNR}" -eq 1 ]]; then
   exec startx "${XINITRC}"
fi
