#!/usr/bin/env bash

autostart=(
   "unclutter --exclude-root"
   "bar -t 5"
   dunst
)

for cmd in "${autostart[@]}"; do
   pidof -s "$(echo "$cmd" | cut -d" " -f1)" || $cmd &
done

tv off
setbg
dim r
key-speed
ssh-agent dwm
