#!/usr/bin/env bash

case $1 in
    set) amixer -D pulse sset Master $2;;
    up) amixer -D pulse sset Master 5%+;;
    down) amixer -D pulse sset Master 5%-;;
    mute) amixer -D pulse sset Master toggle;;
    *) echo "Usage: volume.sh up|down|mute"
esac
bar
