#!/usr/bin/env bash

case $1 in
    set) amixer sset Master $2;;
    up) amixer sset Master 5%+;;
    down) amixer sset Master 5%-;;
    mute) amixer sset Master toggle;;
    *) echo "Usage: volume.sh up|down|mute"
esac
bar
