#!/usr/bin/env bash

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

source "${XDG_CONFIG_HOME:-$HOME/.config}/bash/git-completion.bash"

export CLICOLOR=1
PS1="\[$(tput bold)\]\[$(tput setaf 15)\][\[$(tput setaf 3)\]\u\[$(tput setaf 2)\]@\[$(tput setaf 4)\]\h \[$(tput setaf 5)\]\W\[$(tput bold)\]\[$(tput setaf 15)\]]\[$(tput sgr0)\] "
alias ls="ls --color=auto"

alias v="\$EDITOR"
alias g="git"
alias dot="git --git-dir=\$HOME/.dotfiles.git/ --work-tree=\$HOME"
alias gk="gitk --all &"
alias dk="(cd \$HOME/.dotfiles.git/ && gk)"
__git_complete g __git_main
__git_complete dot __git_main
alias l="ls"
alias ll="ls -lh"
alias la="ls -lha"
alias ef=". ef"
